import type { Metadata } from "next";
import { HeaderContainer} from '@/components';
import "./globals.css";



export const metadata: Metadata = {
  title: "PureInvest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <HeaderContainer />
        {children}
      </body>
    </html>
  );
}
